In [ ]:
#to print the dataframe using set of row and column
import pandas as pd
data={ 'apples':[3,2,0,1],'oranges':[0,3,7,2]}
df=pd.DataFrame(data)
df.to_csv('fruits.csv')
df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [ ]:
import pandas as pd
data={'id':[101,102,103,104,105],'Name':['Cherishma','rama','Radha','pranathi','parinitha'],'dept':['cse','ece','aiml','ads','Cse'],'section':[1,2,1,3,1]}
#given vlaues for the row indexs
df=pd.DataFrame(data,index=[11,12,13,14,15])
df
#to print the single index in that dataset
df.loc[15]

id               105
Name       parinitha
dept             Cse
section            1
Name: 15, dtype: object

In [ ]:
import pandas as pd
#index_col this sets the 0column as index
df=pd.read_csv('movies.csv.zip',index_col=0)
df
#displays that many rowss from top
df.head()
df.head(10)
#displays rows from tail
df.tail(20)
#it give information about the data set
df.info()
#shape give number of rows and columns(4803,24)
df.shape
#this gives descreption about the dataset
df.describe
#if any data is repeted (duplicates)
df.drop_duplicates()
#now again print shape
df.shape
#we are adding 2 datasets
x=pd.concat([df,df])
x
x.shape
#eliminated the dupilcates
x=x.drop_duplicates()
x.shape
#directly it removes the duplicate sfrom the dataframe
df.drop_duplicates(inplace=True)
x.shape

<class 'pandas.core.frame.DataFrame'>
Index: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4775 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4391 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  cast                  4760 non-null   object
 21  crew                  4803 non-null   object
 22  director              4773 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 900.6+ KB

(4803, 23)

In [ ]:
import pandas as pd
df=pd.read_csv('movies.csv.zip')
#count total nan values
total_nans=df.isna().sum().sum()
#count nan value per column
nans_per_column=df.isna().sum()
print("Total Nans:",total_nans)
print("Nans per column:")
print(nans_per_column)
#eliminates all the null values
df.dropna()
#if column has more null values the delete whole column
df.dropna(axis=1)
df.shape
#filling that null (nan)values with something
df.fillna(0)

Total Nans: 4454
Nans per column:
index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

(4803, 24)

In [ ]:
#creating a dataframe with a list of dictionaries,row indices,column indices
import pandas as pd
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df1=pd.DataFrame(data,index=['first','second'],columns=['a','b'])
df2=pd.DataFrame(data,index=['first','second'],columns=['a','b1'])
print(df1)
print('============')
print(df2)

        a   b
first   1   2
second  5  10
============
        a  b1
first   1 NaN
second  5 NaN

In [ ]:
import pandas as pd
d={'one': pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(d)
#adding a new column to an existing dataframe object
#with column label by passing new series
print("Adding a new column by passing as series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print(df)
print("Adding a new column using the existing columns in dataframe:")
df['four']=df['one']+df['three']
print(df)

Adding a new column by passing as series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Adding a new column using the existing columns in dataframe:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

In [ ]:
import pandas as pd
d={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(d)
print(df[2:4])
#reindexing
df=df.reindex(['a','b','c','d','e','f'])
print(df)

   one  two
c  3.0    3
d  NaN    4
   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
e  NaN  NaN
f  NaN  NaN

In [ ]:
import pandas as pd
#index_col this sets the 0column as index
df=pd.read_csv('tips.csv',index_col=0)
df

,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
total_bill,,,,,,,,,,
16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
import pandas as pd
df=pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
import pandas as pd
import numpy as np
#sample dataset
df=pd.DataFrame({'Age':[25,30,np.nan,40,35],'Department':['HR','Finance','Finance',np.nan,'IT']})
#mean for numeric
print(df)
df['Age'].fillna(df['Age'].mean(),inplace=True)
#mode for categorical
df['Department'].fillna(df['Department'].mode()[0],inplace=True)
print(df)

    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_4614/2573406939.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_4614/2573406939.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna(df['Department'].mode()[0],inplace=True)

In [ ]:
#forward filling
df_ffill=df.copy()
df_ffill.fillna(method='ffill',inplace=True)
print(df_ffill)

    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_4614/594003542.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill.fillna(method='ffill',inplace=True)

In [ ]:
#backward filling
df_bfill=df.copy()
df_bfill.fillna(method='bfill',inplace=True)
print(df_bfill)

    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_4614/975154496.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill.fillna(method='bfill',inplace=True)

In [ ]:
import pandas as pd

# Sample dataset with inconsistent date formats
df = pd.DataFrame({
    'Date': ['2025-01-05', '05/01/2025', 'Jan 5, 2025', '2025.01.05']
})

# Convert all dates to standard ISO format (YYYY-MM-DD)
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

print(df)

         Date
0  2025-01-05
1         NaN
2         NaN
3         NaN

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'BOB', 'charlie', 'DAVID']
})

# Convert all names to lowercase
df['Name_lower'] = df['Name'].str.lower()
print(df)

# Convert all names to uppercase
df['Name_upper'] = df['Name'].str.upper()

print(df)

      Name Name_lower
0    Alice      alice
1      BOB        bob
2  charlie    charlie
3    DAVID      david
      Name Name_lower Name_upper
0    Alice      alice      ALICE
1      BOB        bob        BOB
2  charlie    charlie    CHARLIE
3    DAVID      david      DAVID

In [ ]:
import numpy as np
import pandas as pd
from scipy.spatial import distance

pointA = np.array([2,4,6])
pointB = np.array([5,1,9])

# Euclidean Distance
euclidean_distance = distance.euclidean(pointA, pointB)
print("Euclidean Distance:", euclidean_distance)

# Similarity (inverse distance)
similarity = 1 / (1 + euclidean_distance)
print("Similarity:", similarity)

# Manhattan Distance
manhattan_distance = distance.cityblock(pointA, pointB)
print("Manhattan Distance:", manhattan_distance)

# Similarity (inverse distance)
similarity = 1 / (1 + manhattan_distance)
print("Similarity:", similarity)


#Minkowski Distance with p=3
minkowski_distance = distance.minkowski(pointA, pointB, p=2)
print("Minkowski Distance (p=3):", minkowski_distance)

#similarty(inverse of distance)
similarity_minkowski = 1 / (1 + minkowski_distance)
print("Similarity (p=2):", similarity_minkowski)

Euclidean Distance: 5.196152422706632
Similarity: 0.16139047779640892
Manhattan Distance: 9
Similarity: 0.1
Minkowski Distance (p=3): 5.196152422706632
Similarity (p=2): 0.16139047779640892

In [ ]:
#statistical for data frame

import pandas as pd
df=pd.DataFrame({
    'X':[10,20,30,40,50],
    'Y':[15,25,35,45,55] })
#Pearson correltion matrix
corr_matrix=df.corr(method='pearson')
print("Person correlation Matrix:\n",corr_matrix)

Person correlation Matrix:
      X    Y
X  1.0  1.0
Y  1.0  1.0

In [13]:
# Statistical analysis for dataset
import pandas as pd
from scipy.stats import pearsonr

tips = pd.read_csv('tips.csv')

corr, p_value = pearsonr(tips['total_bill'], tips['tip'])

print("Correlation coefficient:", corr)
print("P-value:", p_value)

Correlation coefficient: 0.6757341092113647
P-value: 6.692470646863279e-34

In [14]:
import pandas as pd
from scipy.stats import spearmanr
df=pd.DataFrame({
    'X':[10,20,30,40,50],
    'Y':[15,25,35,45,55] })

#Spearman correlation coefficient and p-value

corr_value,p_value=spearmanr(df['X'],df['Y'])
print(f"Correlation coefficient:{corr_value}")
print(f"P-value:{p_value}")

Correlation coefficient:0.9999999999999999
P-value:1.4042654220543672e-24

In [15]:
#Spearman correlation for data set

import pandas as pd
from scipy.stats import spearmanr

df = pd.read_csv('tips.csv')
corr_value,p_value=spearmanr(df['total_bill'],df['tip'])
print(f"Correlation coefficient:{corr_value}")
print(f"P-value:{p_value}")

Correlation coefficient:0.6789681219001009
P-value:2.501158440923619e-34

In [16]:
def hamming_distance(str1, str2):
    # Ensure strings are of equal length
    if len(str1) != len(str2):
        raise ValueError("Strings must have equal length")

    # Count differing positions
    return sum(ch1 != ch2 for ch1, ch2 in zip(str1, str2))


s1 = "sunandan"
s2 = "sunandan"

dist = hamming_distance(s1, s2)

print(f"Hamming Distance between '{s1}' and '{s2}' : {dist}")

Hamming Distance between 'sunandan' and 'sunandan' : 0

In [26]:
#jaccard_index
def jaccard_index(str1, str2):
    set1, set2 = set(str1.split()), set(str2.split())
    intersection = set1.intersection(set2)
    union = set1.union(set2)
    return len(intersection) / len(union)

s1 = "data science is fun"
s2 = "science makes data useful"

print("Jaccard Index:", jaccard_index(s1, s2))

Jaccard Index: 0.3333333333333333

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Example sentences
s1 = "data science is fun"
s2 = "science makes data useful"

# Convert text to vector representation
vectorizer = CountVectorizer().fit([s1, s2])
vectors = vectorizer.transform([s1, s2])

# Compute cosine similarity
cos_sim = cosine_similarity(vectors[0], vectors[1])[0][0]

print("Cosine Similarity:", cos_sim)

Cosine Similarity: 0.5

In [ ]:
def lcs_length(X,Y):
  m,n=len(X),len(Y)
  dp=[[0] *(n+1) for_in range(m+1)]
  #Build the matrix
  for i  in range(m):
    for j in range(n):
      if X[i] == Y[j]:
        dp[i+1][j+1]=dp[i][j]+1
      else:
        dp[i+1][j+1]=max(dp[i][j+1],dp[i+1][j])
  return dp[m][n]
  seq1="ABCDEF"
  seq2="AEBDF"
  length=lcs_length(seq1,seq2)
  print(f"Longest Common Subsequence length btw "